[manager]
prepend_keymap = [
	{ on = "<Enter>",   run = "open --interactive", desc = "Open selected files" },
]
append_keymap = [
	# { on = [ "g", "o" ],       run = "cd C:/Users/wanvi/OneDrive/Documents",   desc = "Goto ~/Documents" },
	# { on = [ "g", "e" ],       run = "cd C:/dev",   desc = "Goto ~/Dev" },

	{ on = [ "g", "o" ],       run = "cd /mnt/c/Users/wanvi/OneDrive/Documents",   desc = "Goto Documents" },
	{ on = [ "g", "u" ],       run = "cd /mnt/c/Users/wanvi/Downloads",   desc = "Goto Downloads" },
	{ on = [ "g", "e" ],       run = "cd /mnt/c/dev",   desc = "Goto Dev" },
	{ on = [ "g", "w" ],       run = "cd /mnt/c/Users/wanvi",   desc = "Goto Windows Home" },
        { on = [ "g", "s" ],       run = "cd ~/.ssh/",   desc = "Goto SSH folder" },

        { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  
	{ on = [ "C", "a"],   run = "plugin compress ", desc = "Archive selected files" },
	{ on = [ "C", "c" ],   run = "plugin ouch -- zip", desc = "Compress with ouch" },	

	{ on = [ "c", "m" ], run = "plugin chmod",  desc = "Chmod on selected files" },

	{ on = [ "R", "p", "p" ], run = "plugin sudo -- paste",  desc = "sudo paste" },
	{ on = [ "R", "P" ], run = "plugin sudo -- paste --force",  desc = "sudo paste force" },
	{ on = [ "R", "r" ], run = "plugin sudo -- rename",  desc = "sudo rename" },
	{ on = [ "R", "p", "l" ], run = "plugin sudo -- link",  desc = "sudo link" },
	{ on = [ "R", "p", "r" ], run = "plugin sudo -- link --relative",  desc = "sudo link relative path" },
	{ on = [ "R", "p", "L" ], run = "plugin sudo -- hardlink",  desc = "sudo hardlink" },
	{ on = [ "R", "a" ], run = "plugin sudo -- create",  desc = "sudo create" },
	{ on = [ "R", "d" ], run = "plugin sudo -- remove",  desc = "sudo trash" },
        { on = [ "R", "D" ], run = "plugin sudo -- remove --permanently",  desc = "sudo delete  permanently" },
]
